### ISSUE TITLE
When in a sub-company using Change option on the menu doesn't give a list of sub-companies

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/common-header#545]
**Problem**
User can't easily navigate between sub-companies and has to return to parent company in order to select another.

**User Stories**
As a user I can click _change_ and see the list of the parent's sub-companies
As a user I can navigate from a sub-company to another without returning to the parent company

**Comment by ByronDarlison** [comment]
@ghislaineguerin I believe this is now fixed. Can you review and confirm.

**Comment by ghislaineguerin** [comment]
@ByronDarlison not fixed, but it wasn't implemented as I had intended (change shows list of sub-companies again) instead it shows a blank list of sub-companies from a sub company.

**Comment by ByronDarlison** [comment]
@ghislaineguerin can you revise the defect description to describe how it works now and include how it should work and can you clarify if you have ux work to do to make this correction?

**Comment by ghislaineguerin** [comment]
@ByronDarlison I have updated the description

**Comment by ByronDarlison** [comment]
@ghislaineguerin do you think this is an issue given our target of 5 displays or less?

**Comment by ghislaineguerin** [comment]
@ByronDarlison not now. I would archive it.

**Comment by ByronDarlison** [comment]
Okay. Closing.
